### ISSUE TITLE
[iOS] CookieManager.get with useWebKit crash if argument is not a url

### ISSUE THREAD

**Issue by frankyjuang** [react-native-community/react-native-cookies#9] opened 2020-01-15 18:54 UTC
# Bug

This crashes.

```typescript
CookieManager.get("google.com", true);
```

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 539.84 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - /var/folders/z1/7nfybp6x3ns9gzz58cm53m480000gn/T/yarn--1579114313928-0.6154963038500227/node
    Yarn: 1.21.1 - /var/folders/z1/7nfybp6x3ns9gzz58cm53m480000gn/T/yarn--1579114313928-0.6154963038500227/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 1.0.1

## Steps To Reproduce

Run this and crash. Won't crash if it's a url like `https://google.com`

```typescript
CookieManager.get("google.com", true);
```

## Reproducible sample code

```typescript
CookieManager.get("google.com", true);
```

**Comment by DIGITALSQUAD** [comment] 2020-01-20 09:35
Same here if url is a localhost.  #12 
Works fine
`CookieManager.get('http://192.168.1.50:3000', true);`

Crash silently
`CookieManager.get('http:/localhost:3001', true);`

**Comment by safaiyeh** [comment] 2020-01-20 15:21
Thanks for the issue @frankyjuang and @DIGITALSQUAD. Putting this in my todo for today

**Comment by safaiyeh** [comment] 2020-01-21 04:43
I narrowed down the issue. What should be the expected behavior? Reject the promise with unsupported URL? or resolve the URL? 

cc @frankyjuang @DIGITALSQUAD

**Comment by safaiyeh** [comment] 2020-01-21 05:31
I put up a PR for the fix. Can one of you confirm the fix by testing the branch? Thanks!

@frankyjuang @DIGITALSQUAD

**Comment by safaiyeh** [comment] 2020-01-26 02:49
Released with v1.1.1 🎉

**Closed by safaiyeh** 2020-01-26 02:49 UTC
Labels: bug, iOS

**Comment by DIGITALSQUAD** [comment] 2020-02-06 10:36
Sorry to be late reply.
This issue is not fixed on version 2.0.3.

**Comment by safaiyeh** [comment] 2020-02-06 15:41
Thanks @DIGITALSQUAD I'll try to reproduce it tonight

**Comment by DIGITALSQUAD** [comment] 2020-02-07 11:38
I'm sorry.  This issue is fixed now💦
The problem was[ the same as before ](https://github.com/react-native-community/cookies/issues/7#issuecomment-575048048)

`react-native link` cannot replace correctly when upgrading package?

**Comment by safaiyeh** [comment] 2020-02-07 14:57
Apparently not, can you create an issue with the CLI team? 

https://github.com/react-native-community/cli
